package com.example.shopservice;

import com.example.shopservice.entity.Order;
import com.example.shopservice.entity.OrderItem;
import com.example.shopservice.entity.Product;
import com.example.shopservice.entity.Review;
import com.example.shopservice.entity.User;
import com.example.shopservice.repository.OrderItemRepository;
import com.example.shopservice.repository.OrderRepository;
import com.example.shopservice.repository.ProductRepository;
import com.example.shopservice.repository.ReviewRepository;
import com.example.shopservice.repository.UserRepository;
import com.example.shopservice.resource.OrderItemResource;
import com.example.shopservice.resource.OrderResource;
import com.example.shopservice.resource.ProductResource;
import com.example.shopservice.resource.ReviewResource;
import com.example.shopservice.resource.UserResource;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.asset.StringAsset;
import org.jboss.shrinkwrap.api.spec.WebArchive;

/**
 * Factory that creates a ShrinkWrap {@link WebArchive} used by all Arquillian tests.
 *
 * <p>The archive contains:
 * <ul>
 *   <li>All application classes (entities, repositories, JAX-RS resources, application class).</li>
 *   <li>{@link TestDataSourceProducer} — registers the JDBC datasource via
 *       {@code @DataSourceDefinition(name="java:app/jdbc/shopservice")} so it is visible
 *       to GlassFish's JNDI validator before deployment validation runs. The datasource
 *       uses {@code org.openjproxy.jdbc.OjpDataSource} routing through a local OJP proxy to
 *       an H2 in-memory backend.</li>
 *   <li>A test-specific {@code persistence.xml} configured for H2 with drop-and-create.</li>
 * </ul>
 */
public final class DeploymentFactory {

    private DeploymentFactory() {}

    public static WebArchive createDeployment() {
        return ShrinkWrap.create(WebArchive.class, "shopservice.war")
                // Application entry point
                .addClass(ShopServiceApplication.class)
                // Test datasource registration via @DataSourceDefinition (OjpDataSource → H2 via OJP)
                .addClass(TestDataSourceProducer.class)
                // Entities
                .addClass(User.class)
                .addClass(Product.class)
                .addClass(Order.class)
                .addClass(OrderItem.class)
                .addClass(Review.class)
                // Repositories
                .addClass(UserRepository.class)
                .addClass(ProductRepository.class)
                .addClass(OrderRepository.class)
                .addClass(OrderItemRepository.class)
                .addClass(ReviewRepository.class)
                // JAX-RS resources
                .addClass(UserResource.class)
                .addClass(ProductResource.class)
                .addClass(OrderResource.class)
                .addClass(OrderItemResource.class)
                .addClass(ReviewResource.class)
                // Use test persistence.xml (H2, drop-and-create schema)
                .addAsResource("META-INF/persistence-test.xml", "META-INF/persistence.xml")
                // Drop script used by persistence-test.xml; drops tables in FK-safe order (children first)
                .addAsResource("META-INF/drop.sql", "META-INF/drop.sql")
                // Create script used by persistence-test.xml; uses GENERATED BY DEFAULT AS IDENTITY
                // so auto-increment is preserved correctly when forwarded through the OJP gRPC proxy
                .addAsResource("META-INF/create.sql", "META-INF/create.sql")
                // Explicit CDI activation with annotated discovery mode.
                // EmptyAsset.INSTANCE (0-byte beans.xml) would trigger bean-discovery-mode="all",
                // which causes Weld to proxy server-side built-in beans (jakarta.transaction.UserTransaction)
                // that are invisible from the WAR classloader in GlassFish Embedded — WELD-001524.
                // "annotated" mode discovers only beans carrying CDI annotations, avoiding that issue.
                .addAsWebInfResource(
                        new StringAsset("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                                + "<beans xmlns=\"https://jakarta.ee/xml/ns/jakartaee\"\n"
                                + "       xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
                                + "       xsi:schemaLocation=\"https://jakarta.ee/xml/ns/jakartaee"
                                + " https://jakarta.ee/xml/ns/jakartaee/beans_4_0.xsd\"\n"
                                + "       version=\"4.0\"\n"
                                + "       bean-discovery-mode=\"annotated\">\n"
                                + "</beans>"),
                        "beans.xml");
    }
}
