-- Create tables in FK-safe order (parent tables first).
-- Using GENERATED BY DEFAULT AS IDENTITY for auto-increment IDs.
-- Each statement is on a single line: EclipseLink's create-source=script reader splits
-- on newlines, so a multi-line statement would be executed line-by-line.
CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, createdat TIMESTAMP, PRIMARY KEY (id), UNIQUE (username), UNIQUE (email));
CREATE TABLE products (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, price NUMERIC(38) NOT NULL, PRIMARY KEY (id));
CREATE TABLE orders (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, orderdate TIMESTAMP NOT NULL, user_id BIGINT, PRIMARY KEY (id), CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE order_items (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id BIGINT NOT NULL, product_id BIGINT NOT NULL, quantity INT NOT NULL, PRIMARY KEY (id), CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id), CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id));
CREATE TABLE reviews (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT NOT NULL, product_id BIGINT NOT NULL, rating INT NOT NULL, comment VARCHAR(1000), PRIMARY KEY (id), CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id), CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id));
