spring.application.name=shop-service-application

### Catalog Datasource Config (high-performance ojp datasource) ###
spring.datasource.catalog.url=jdbc:ojp[localhost:5432(high-performance)]_postgresql://user@localhost/catalog_db
spring.datasource.catalog.username=postgres
spring.datasource.catalog.password=postgres
spring.datasource.catalog.driver-class-name=org.openjproxy.jdbc.Driver
#Sets the datasource to not use hikari CP connection pool and open single connections instead
spring.datasource.catalog.type=org.springframework.jdbc.datasource.SimpleDriverDataSource
spring.jpa.catalog.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.catalog.properties.hibernate.hbm2ddl.auto=create-drop

### Checkout Datasource Config (default ojp datasource) ###
spring.datasource.checkout.url=jdbc:ojp[localhost:5432]_postgresql://user@localhost/checkout_db
spring.datasource.checkout.username=postgres
spring.datasource.checkout.password=postgres
spring.datasource.checkout.driver-class-name=org.openjproxy.jdbc.Driver
#Sets the datasource to not use hikari CP connection pool and open single connections instead
spring.datasource.checkout.type=org.springframework.jdbc.datasource.SimpleDriverDataSource
spring.jpa.checkout.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.checkout.properties.hibernate.hbm2ddl.auto=create-drop

#### Global Config ###
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
