# Default datasource
ojp.connection.pool.maximumPoolSize=25
ojp.connection.pool.minimumIdle=5
ojp.connection.pool.connectionTimeout=2000

# High-performance application datasource
high-performance.ojp.connection.pool.maximumPoolSize=50
high-performance-config.ojp.connection.pool.minimumIdle=10
high-performance.ojp.connection.pool.connectionTimeout=5000