name: Spring Boot/Micronaut/Quarkus Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [ojp-updated]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shopservice code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout OJP repository
        uses: actions/checkout@v4
        with:
          repository: Open-JDBC-Proxy/ojp
          fetch-depth: 0
          ref: main
          path: ojp

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      # Clean Maven repository to avoid stale ojp-jdbc-driver artifacts
      - name: Clean ojp-jdbc-driver from local Maven repository
        run: rm -rf ~/.m2/repository/org/openjproxy/ojp-jdbc-driver

      # Build and install ojp-jdbc-driver with integration test SNAPSHOT version
      - name: Set ojp-jdbc-driver version to SNAPSHOT
        run: |
          mvn versions:set -DnewVersion=0.0.1-SNAPSHOT-INT-TEST-TMP-VERSION -pl ojp-jdbc-driver -DgenerateBackupPoms=false
        working-directory: ojp

      - name: Build and install ojp-jdbc-driver with SNAPSHOT version
        run: mvn clean install -pl ojp-jdbc-driver -am -DskipTests
        working-directory: ojp

      # Install remaining ojp modules
      - name: Install remaining ojp modules
        run: mvn clean install -DskipTests
        working-directory: ojp

      - name: Run (ojp-server)
        run: mvn verify -pl ojp-server -Prun-ojp-server > ojp-server.log 2>&1 &
        working-directory: ojp

      - name: Wait for ojp-server to start
        run: sleep 10


      - name: Run OJP Spring Boot Integration tests (shopservice)
        run: mvn clean verify
        working-directory: spring-boot/shopservice

      - name: Run OJP Quarkus Integration tests (shopservice)
        run: mvn clean verify
        working-directory: quarkus/shopservice

      - name: Run OJP Micronaut Integration tests (shopservice)
        run: mvn clean verify
        working-directory: micronaut/shopservice